# Generated by Django 4.2.7 on 2023-11-25 21:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = []
